<div id="leftColumn">
    <div id="box">
        <div class="inner">
            <div class="title"><a href="">Menu</a></div>
            <ul class="list">
                <li><span><a href="<?php echo Utils::createLink('admin-home'); ?>"><img src="../admin/img/icons/house.png" alt="Home" title="Home" class="icon" />Home</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('admin-edit'); ?>"><img src="../admin/img/icons/user_edit.png" alt="Edit Profile" title="Edit Profile" class="icon" />Edit profile</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('admin-view'); ?>"><img src="../admin/img/icons/user.png" alt="Profile" title="Profile" class="icon" />Profile</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('admin-result-pie'); ?>"><img src="../admin/img/icons/chart_pie.png" alt="See Result" title="See Result" class="icon" />Result</a></span></li>

                <li><span><a href="<?php echo Utils::createLink('admin-list-voter'); ?>"><img src="../admin/img/icons/folder_user.png" alt="View voters" title="View voters" class="icon" />View Voters</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('admin-list-candidate'); ?>"><img src="../admin/img/icons/folder_user.png" alt="View Candidates" title="View candidate" class="icon" />View Candidates</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('admin-list-university'); ?>"><img src="../admin/img/icons/world.png" alt="View Universities" title="View University" class="icon" />View Universities</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('admin-list-faculty'); ?>"><img src="../admin/img/icons/building.png" alt="View faculty" title="View faculty" class="icon" />View Faculties</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('admin-list-department'); ?>"><img src="../admin/img/icons/application_home.png" alt="Add Department" title="Add Department" class="icon" />View Departments</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('admin-list-election'); ?>"><img src="../admin/img/icons/time.png" alt="View Election" title="View Election" class="icon" />View Elections</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('admin-list-position'); ?>"><img src="../admin/img/icons/medal_gold_3.png" alt="View Position" title="View Position" class="icon" />View Position</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('admin-list-administrator'); ?>"><img src="../admin/img/icons/folder_user.png" alt="View Admin" title="View Administrator" class="icon" />View Administrators</a></span></li>

               <?php
                if ($currentAdmin->getRole() === 'super') {
                    ?>

                    <li><span><a href="<?php echo Utils::createLink('voter-register'); ?>"><img src="../admin/img/icons/user_add.png" alt="Add voter" title="Add voter" class="icon" />Add Voter</a></span></li>
                    <li><span><a href="<?php echo Utils::createLink('candidate-register'); ?>"><img src="../admin/img/icons/user_add.png" alt="Add candidate" title="Add candidate" class="icon" />Add Candidate</a></span></li>
                    <li><span><a href="<?php echo Utils::createLink('add-edit-university'); ?>"><img src="../admin/img/icons/world_add.png" alt="Add University" title="Add University" class="icon" />Add University</a></span></li>
                    <li><span><a href="<?php echo Utils::createLink('add-edit-faculty'); ?>"><img src="../admin/img/icons/building_add.png" alt="Add faculty" title="Add faculty" class="icon" />Add Faculty</a></span></li>
                    <li><span><a href="<?php echo Utils::createLink('add-edit-department'); ?>"><img src="../admin/img/icons/application_add.png" alt="Add Department" title="Add Department" class="icon" />Add Department</a></span></li>
                    <li><span><a href="<?php echo Utils::createLink('add-edit-election'); ?>"><img src="../admin/img/icons/time_add.png" alt="Add Election" title="Add Election" class="icon" />Add Election</a></span></li>
                    <li><span><a href="<?php echo Utils::createLink('add-edit-position'); ?>"><img src="../admin/img/icons/medal_gold_add.png" alt="Add Position" title="Add position" class="icon" />Add Position</a></span></li>
                    <li><span><a href="<?php echo Utils::createLink('admin-add'); ?>"><img src="../admin/img/icons/user_add.png" alt="Add Admin" title="Add Election" class="icon" />Add Administrator</a></span></li>
                    <li><span><a href="<?php echo Utils::createLink('admin-result'); ?>"><img src="../admin/img/icons/report.png" alt="Report" title="report" class="icon" />Report</a></span></li>
                    <?php
                }
                ?>
                    <li class="last"><span><a href="<?php echo Utils::createLink('admin-login', array('logout' => 0)); ?>"><img src="../admin/img/icons/door_out.png" alt="Log out" title="Log out" class="icon" />Logout</a></span></li>
            </ul>
        </div>

    </div>

</div>
<div id="rightColumn">
    <div id="content">
        <div class="indent">
            <h3><?php if ($edit): ?>
                    <?php echo 'Edit: ' . Utils::escape($position->getName()); ?>
                <?php else: ?>
                    Add new Position
                <?php endif; ?></h3>
            <?php if (!empty($errors)): ?>
                <div class="ui-widget">
                    <div class="ui-state-error ui-corner-all" style="padding: auto;"> 
                        <ul class="errors">
                            <?php foreach ($errors as $error): ?>
                                <?php /* @var $error Error */ ?>
                                <li><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .1em;"></span><?php echo $error->getMessage(); ?></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            <?php endif; ?>
            <div class="form">
                <form name="" action="" method="post">
                    <table border="0">
                        <tbody>
                            <tr>
                                <td><label>Name</label></td>
                                <td><div class="input-container">
                                        <input name="data[name]" id="" type="text"
                                               value="<?php
                                               echo (isset($_POST['data']['name'])) ? htmlspecialchars(
                                                               $_POST['data']['name']) : $position->getName();
                                               ?>" class="text<?php echo Utils::error_field('name', $errors); ?>"/></div></td>
                            </tr>
                            <tr>
                                <td><label>Level</label></td>
                                <td><div class="input-container">
                                        <select name="data[level]" class="university" id="university">
                                            <option>--Select Level--</option>
                                            <?php
                                            foreach ($levels as $level) {
                                                ?>
                                                <option value="<?php echo $level; ?>"
                                                <?php
                                                if (isset($_POST['data']['level']) && ($_POST['data']['level']) == $level) {
                                                    echo 'selected="selected"';
                                                }elseif ($edit && ($position->getPositionLevel() == $level)) {
                                                     echo 'selected="selected"';
                                                }
                                                ?>><?php echo $level; ?></option>
                                                        <?php
                                                    }
                                                    ?>
                                        </select></div>
                                </td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><input name="save" value="SAVE" type="submit" class="greenButton"/>
                                    <input name="cancel" value="CANCEL" type="submit" class="greenButton"/></td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            </div>

        </div>
    </div>
</div>