<div id="leftColumn">
    <div id="box">
        <div class="inner">
            <div class="title"><a href="">Menu</a></div>
            <ul class="list">
                <li><span><a href="<?php echo Utils::createLink('candidate-home'); ?>"><img src="img/icons/house.png" alt="Home" title="Home" class="icon" />Home</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('candidate-edit'); ?>"><img src="img/icons/user_edit.png" alt="Edit Profile" title="Edit Profile" class="icon" />Edit profile</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('candidate-view'); ?>"><img src="img/icons/user.png" alt="Profile" title="Profile" class="icon" />Profile</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('candidate-result'); ?>"><img src="img/icons/chart_pie.png" alt="See Result" title="See Result" class="icon" />Result</a></span></li>
                <li class="last"><span><a href="<?php echo Utils::createLink('candidate-login', array('logout' => 0)); ?>"><img src="img/icons/door_out.png" alt="Log out" title="Log out" class="icon" />Logout</a></span></li>
            </ul>
        </div>

    </div>

</div>
<div id="rightColumn">
    <div id="content">
        <div class="indent">
            <h1>Welcome!</h1>
            <p class="p">Welcome to <b>Cluster F2 online Voting System</b>.</p>
            <p class="p">Use the menu on the left to navigate through the site.</p>
        </div>
    </div>
</div>